"""
Out-of-distribution (OOD) detection for inference inputs.

Checks numeric features against the training data bounds.
If any feature falls outside the training range, the API response
includes ood_warning=True so the downstream system can decide
whether to trust the prediction.

This is a lightweight range check, not a full distributional test.
It catches the most common failure mode: a data pipeline error that
sends a LOS of 365 days or a comorbidity index of 15.
"""

from typing import Any

# Training data bounds per numeric feature.
# Source: generated by scripts/generate-dataset.py with seed=42.
# Update these bounds if the training data distribution changes.
TRAINING_BOUNDS: dict[str, tuple[int, int]] = {
    "comorbidity_index": (0, 6),
    "length_of_stay_days": (1, 30),
    "prior_admissions_12m": (0, 10),
    "procedure_count": (0, 15),
    "specialist_consult_ct": (0, 10),
}


def check_ood(record_dict: dict[str, Any]) -> bool:
    """
    Return True if any numeric feature is outside the training range.

    Only checks features with known bounds (numeric fields).
    Categorical features are validated by Pydantic enum constraints upstream.

    Args:
        record_dict: Feature dict with imputation already applied (no None values).

    Returns:
        True if at least one feature is out of the training distribution.
    """
    for feature, (low, high) in TRAINING_BOUNDS.items():
        value = record_dict.get(feature)
        if value is not None and (value < low or value > high):
            return True
    return False


def get_ood_features(record_dict: dict[str, Any]) -> list[str]:
    """
    Return the names of features that are outside the training range.
    Used for detailed diagnostics; not included in the API response
    (ood_warning is a single boolean flag per the response schema).

    Args:
        record_dict: Feature dict with imputation already applied.

    Returns:
        List of feature names that are out of distribution.
    """
    ood_features = []
    for feature, (low, high) in TRAINING_BOUNDS.items():
        value = record_dict.get(feature)
        if value is not None and (value < low or value > high):
            ood_features.append(feature)
    return ood_features
